In [14]:
from sklearn import svm, datasets
import numpy as np
iris= datasets.load_iris()

In [15]:
import pandas as pd
df=pd.DataFrame(iris.data, columns=iris.feature_names)
df["flower"]=iris.target
df["flower"]=df["flower"].apply(lambda x: iris.target_names[x])
df.head(6)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   
5                5.4               3.9                1.7               0.4   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa  
5  setosa

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test= train_test_split(iris.data, iris.target, test_size=0.3)

In [17]:
# hypertuning SVM
model=svm.SVC(kernel="rbf", C=30, gamma="auto")
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.9111111111111111

In [18]:
from sklearn.model_selection import cross_val_score

In [19]:
cross_val_score(svm.SVC(kernel="linear", C=10, gamma="auto"), iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [20]:
cross_val_score(svm.SVC(kernel="rbf", C=10, gamma="auto"), iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [21]:
cross_val_score(svm.SVC(kernel="linear", C=20, gamma="auto"), iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.93333333, 1.        ])

In [22]:
kernels= ["rbf", "linear"]
C=[1,10,20]
avg_scores={}
for kval in kernels:
    for cval in C:
        cv_scores= cross_val_score(svm.SVC(kernel=kval, C=cval, gamma="auto"), iris.data, iris.target, cv=5)
        avg_scores[kval + '_' + str(cval)]= np.average(cv_scores)

avg_scores


{'rbf_1': np.float64(0.9800000000000001),
 'rbf_10': np.float64(0.9800000000000001),
 'rbf_20': np.float64(0.9666666666666668),
 'linear_1': np.float64(0.9800000000000001),
 'linear_10': np.float64(0.9733333333333334),
 'linear_20': np.float64(0.9666666666666666)}

In [ ]:
# Previous methods are not efficients 
# We use GridsearchCV

In [23]:
from sklearn.model_selection import GridSearchCV

clf= GridSearchCV(svm.SVC(gamma="auto") , {
    "C": [1,10,20], 
    "kernel": ["rbf", "linear"]
} , cv=5 , return_train_score=False  )#gamma is not tunned
clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00152206, 0.00097504, 0.00100274, 0.00111256, 0.00095229,
        0.00093579]),
 'std_fit_time': array([8.59437529e-04, 7.04268628e-05, 6.26955462e-05, 3.13002739e-04,
        8.63351040e-05, 1.62176867e-04]),
 'mean_score_time': array([0.00078869, 0.00073824, 0.00064363, 0.00072126, 0.00073514,
        0.00066652]),
 'std_score_time': array([2.86897230e-04, 6.46631625e-05, 1.78750981e-05, 1.91697101e-04,
        1.09644617e-04, 1.39264257e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
 

In [ ]:
# convert the results to data

In [26]:
df_=pd.DataFrame(clf.cv_results_)
df_

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0       0.001522      0.000859         0.000789        0.000287        1   
1       0.000975      0.000070         0.000738        0.000065        1   
2       0.001003      0.000063         0.000644        0.000018       10   
3       0.001113      0.000313         0.000721        0.000192       10   
4       0.000952      0.000086         0.000735        0.000110       20   
5       0.000936      0.000162         0.000667        0.000139       20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [27]:
df_[["param_C", "param_kernel", "mean_test_score"]]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667

In [28]:
dir(clf)

['__abstractmethods__',
 '__annotate_func__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_build_request_for_signature',
 '_check_refit_for_multimetric',
 '_check_scorers_accept_sample_weight',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_estimator_type',
 '_format_results',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params_html',
 '_get_routed_params_for_fit',
 '_get_scorers',
 '_html_repr',
 '_parameter_constraints',
 '_repr_html_',
 '_re

In [29]:
clf.best_score_

np.float64(0.9800000000000001)

In [30]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [31]:
from sklearn.model_selection import RandomizedSearchCV

In [32]:
rs= RandomizedSearchCV(svm.SVC(gamma="auto") , {
    "C": [1,10,20], 
    "kernel": ["rbf", "linear"]
} , cv=5 , return_train_score=False  , n_iter= 2 )# choose the number of random permutation
rs.fit(iris.data, iris.target)
rs.cv_results_
pd.DataFrame(rs.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.000885      0.000340         0.000517        0.000142       linear   
1       0.001349      0.000317         0.000964        0.000290          rbf   

   param_C                         params  split0_test_score  \
0       10  {'kernel': 'linear', 'C': 10}           1.000000   
1        1      {'kernel': 'rbf', 'C': 1}           0.966667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.900000           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.973333        0.038873                2  
1         0.980000        0.016330                1

# Choose best model

In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [38]:
model_params= {
    "svm": {  
        "model": svm.SVC(gamma="auto"),
        "params" :{
            "C": [1,10,20],
            "kernel": ["rbf", "linear"]
                  }
            },
    
    "random_forest": {  
        "model": RandomForestClassifier(),
        "params" :{
            "n_estimators": [1,5,10],
                  }
            },
    
        "logistic_regression": {  
        "model": LogisticRegression(solver="liblinear", multi_class="auto"),
        "params" :{
            "C": [1,5,10]
                  }
            }
}

In [42]:
score=[]

for model_name, mp in model_params.items():
    clf=GridSearchCV(mp["model"], mp["params"],cv=5, return_train_score= False)
    clf.fit(iris.data, iris.target)
    score.append({
        "model": model_name,
        "best_score": clf.best_score_,
        "best_params": clf.best_params_
    })

C:\Users\loic\miniforge3\envs\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\loic\miniforge3\envs\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:1296: FutureWarning: Using the 'liblinear' solver for multiclass classification is deprecated. An error will be raised in 1.8. Either use another solver which supports the multinomial loss or wrap the estimator in a OneVsRestClassifier to keep applying a one-versus-rest scheme.
  warnings.warn(
C:\Users\loic\miniforge3\envs\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
C:\Users\loic\miniforge3\en

In [43]:
df=pd.DataFrame(score, columns=["model", "best_score","best_params"])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}