In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits= load_digits()

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(digits.data, digits.target, test_size=0.3)

In [15]:
lr=LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

C:\Users\loic\miniforge3\envs\ML\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9722222222222222

In [16]:
svm=SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9833333333333333

In [17]:
rf=RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9666666666666667

In [18]:
# With train_test_split we can't run one time an choose the best model as the initial sample change at each iteration

In [25]:
# Use K fold
from sklearn.model_selection import KFold
kf= KFold(n_splits=3) # Number of fold
kf


KFold(n_splits=3, random_state=None, shuffle=False)

In [26]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [27]:
def get_score(model, X_train, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [78]:
from sklearn.model_selection import StratifiedKFold
folds= StratifiedKFold(n_splits=10)
folds


StratifiedKFold(n_splits=10, random_state=None, shuffle=False)

In [79]:
scores_l=[]
scores_svm=[]
scores_rf=[]

for train_index, test_index in folds.split(digits.data, digits.target):
    
    X_train, X_test, y_train, y_test= digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(max_iter=200),X_train, y_train, y_test ))     
    scores_svm.append(get_score(SVC(), X_train, y_train, y_test ))    
    scores_rf.append(get_score(RandomForestClassifier(), X_train, y_train, y_test ))    
    
    

In [80]:
scores_l

[0.9055555555555556,
 0.95,
 0.8888888888888888,
 0.9333333333333333,
 0.9388888888888889,
 0.9611111111111111,
 0.9444444444444444,
 0.9441340782122905,
 0.8715083798882681,
 0.9385474860335196]

In [81]:
scores_svm

[0.9444444444444444,
 0.9888888888888889,
 0.9277777777777778,
 0.9666666666666667,
 0.9833333333333333,
 0.9888888888888889,
 0.9888888888888889,
 0.994413407821229,
 0.9608938547486033,
 0.9553072625698324]

In [82]:
scores_rf

[0.9055555555555556,
 0.9666666666666667,
 0.9611111111111111,
 0.9222222222222223,
 0.9555555555555556,
 0.9722222222222222,
 0.9722222222222222,
 0.9664804469273743,
 0.9385474860335196,
 0.9385474860335196]

In [83]:
# We can simply use crossvalscore

from sklearn.model_selection import cross_val_score

In [84]:
cross_val_score(LogisticRegression(max_iter=200),digits.data, digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.94150418, 0.89693593])

In [86]:
cv = StratifiedKFold(n_splits=10) # to get the same result as previously
cross_val_score(LogisticRegression(max_iter=200), digits.data, digits.target, cv=cv)

array([0.90555556, 0.95      , 0.88888889, 0.93333333, 0.93888889,
       0.96111111, 0.94444444, 0.94413408, 0.87150838, 0.93854749])

In [ ]:
#cross_val_score(LogisticRegression(), digits.data, digits.target, cv=10)
#cv = StratifiedKFold(n_splits=3)
#cross_val_score(LogisticRegression(), digits.data, digits.target, cv=cv)


In [87]:
cross_val_score(SVC(),digits.data, digits.target) #

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])